# Default Sinntelligence Python code quality workflow for our Github repos.

name: General Python code quality

on:
  workflow_call:

env:
  TISCAMERA_DL_LINK_LATEST: https://github.com/TheImagingSource/tiscamera/releases/download/v-tiscamera-1.1.1/tiscamera_1.1.1.4142_amd64_ubuntu_1804.deb
  TISCAMERA_DL_LINK_V1.1.1: https://github.com/TheImagingSource/tiscamera/releases/download/v-tiscamera-1.1.1/tiscamera_1.1.1.4142_amd64_ubuntu_1804.deb
  TISCAMERA_DL_LINK_V1.0.0: https://github.com/TheImagingSource/tiscamera/releases/download/v-tiscamera-1.0.0/tiscamera_1.0.0.4005_amd64_ubuntu_1804.deb
  
jobs:
  codetest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3   

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Update python
      run: |
        sudo apt update
        python -m pip install --upgrade pip
        python -m pip install flake8 pylint pytest black

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run CI setup shell script
      run: |
        if [ ! -d .ci ]; then mkdir .ci; fi
        if [ -f .ci/setup.sh ]; then chmod +x .ci/setup.sh; .ci/setup.sh; fi

    - name: Test with pytest
      run: |
        if [ ! -d test ]; then mkdir test; fi
        sh -c 'python -m pytest test/unit -k "test_camera_manager"; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
