# Default Sinntelligence Python code quality workflow for our Github repos.

name: General Python code quality - DEPRECATED

on:
  workflow_call:
  
jobs:
  codetest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Display deprecation message
      run: |
        echo "WARNING: This workflow is deprecated and no longer maintained."
        echo "Please update your references to use the new workflow location in the private sinntelligence repository."
        exit 1
