# Default Sinntelligence Python code quality workflow for our Github repos.

name: General Python code quality

on:
  workflow_call:
    secrets:
      SINNTELLIGENCE_REPO_SSH_KEY:
        required: true
        
jobs:
  codetest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3   

    - name: Install sinntelligence repo SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SINNTELLIGENCE_REPO_SSH_KEY }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pytest black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run CI setup shell script
      run: |
        if [ -f .ci/setup.sh ]; then chmod +x .ci/setup.sh; .ci/setup.sh; fi

    - name: Lint with flake8
      run: |
        flake8_ignored="E203,E401,E402,W503"
        flake8 . --count --ignore=$flake8_ignored --show-source --max-complexity=20 --max-line-length=120 --statistics

    - name: Lint with pylint
      run: |
        if [ ! -f .ci/pylintrc ]; then touch .ci/pylintrc; fi
        pylint_disabled="W0613,R0903,R0913,R0914,C0103,F0401,R0902,C0413,C0411,W0703,R1723,R1734,R1735,R1728,W1514,R0912,W1203,R0801"
        pylint --rcfile=.ci/pylintrc --jobs=0 --disable=$pylint_disabled --max-line-length=120 --enable=unused-import $(git ls-files '*.py')        

    - name: Code formatting with black
      run: |
        black --diff --check --line-length=120 $(git ls-files '*.py')

    - name: Test with pytest
      run: |
        sh -c 'pytest; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
